# Generated by Django 3.0.8 on 2020-07-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='updatd_at',
            new_name='updated_at',
        ),
    ]
